### ISSUE TITLE
rerun only errors, not failures

### ISSUE THREAD

**Issue by sashakruglov** [gocept/pytest-rerunfailures#18]
hey @klrmn 

is it possible to rerun only errors, not failures?
is it possible to develop additional switch/hook to allow rerun only of errors?

thanks in advance,

**Comment by florianpilz** [comment]
Hi sashakruglov! We (gocept) have accepted the ownership of pytest-rerunfailures and are the new maintainers.

Why do you want to rerun errors only? It should not matter if it was an error or a failure, since this only depends on the error handling. So both could have the same cause for different code paths. In addition, it should not be a concern for speed, since there shouldn't be too many broken tests anyway. So feel free to elaborate. :)

**Comment by florianpilz** [comment]
Closing the issue, since there seems to be no interested anymore.

**Comment by mehmetg** [comment]
Would it be possible to rerun only on certain errors like done junit and testng syle retry rules/retry analyzers?

**Comment by florianpilz** [comment]
Currently that is not possible. The more general solution for "selective" reruns would probably to rerun on certain tags. However, I see no harm done by rerunning *all* tests if they fail. So I'm not eager to implement a selective rerun. ;-)

**Comment by mehmetg** [comment]
There are some use cases that may apply, but none of which are crucial and tags should suffice for those.
Thank you.
